version: '3'
services: 
  cron2:
    build: .
    ports:
      - 80:80
    command: sh -c "sh /app/server.sh"
    volumes:
      - ./:/app
    env_file:
       - ./.env
  worker:
    build: .
    command: sh -c "chmod +x /app/worker.sh && sh /app/worker.sh"
    env_file:
     - ./.env
  consumer1:
    build: .
    command: sh -c "chmod +x /app/worker.sh && sh /app/consumer.sh"
    env_file:
      - ./.env
  consumer2:
    build: .
    command: sh -c "chmod +x /app/worker.sh && sh /app/consumer.sh"
    env_file:
      - ./.env








  





