version: '3'
services:
  cron2:
    depends_on:
      - worker
    build: .
    ports:
      - 80:80
    command: sh -c "sh server.sh"
    volumes:
      - ./:/app
    env_file:
      - ./.env
  worker:
    depends_on:
      - consumer1
      - consumer2
    build: .
    command: sh -c "sh worker.sh"
    env_file:
      - ./.env
  consumer1:
    build: .
    command: sh -c "sh consumer.sh"
    env_file:
      - .
