version: '3'
services:
  cron2:
    depends_on:
      - worker
    build: .
    ports:
      - 80:80
    command: sh -c "sh server.sh"
    volumes:
      - ./:/app
    env_file:
      - ./.env
    environment:
      - MONGODB_URL=mongodb://mongo:27017
  worker:
    restart: unless-stopped
    depends_on:
      - consumer
    build: .
    command: sh -c "sh worker.sh"
    env_file:
      - ./.env
    environment:
      - MONGODB_URL=mongodb://mongo:27017
  consumer:
    restart: unless-stopped
    build: .
    command: sh -c "sh consumer.sh"
    env_file:
      - ./.env
    environment:
      - MONGODB_URL=mongodb://mongo:27017
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
